# Generated by Django 5.2.1 on 2025-05-24 06:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0002_image_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='students')),
                ('quote', models.TextField(blank=True)),
                ('favorite_sport', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.TextField(blank=True)),
                ('ambitions', models.TextField(blank=True)),
            ],
        ),
    ]
