# Generated by Django 5.2.1 on 2025-05-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0003_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='favorite_teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
