# Generated by Django 5.2.1 on 2025-06-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0005_remove_students_favorite_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefectQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefect_quotes', to='yearbookBackend.students')),
            ],
            options={
                'verbose_name': 'Prefect Quote',
                'verbose_name_plural': 'Prefect Quotes',
            },
        ),
    ]
