# Generated by Django 5.2.1 on 2025-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0008_gallery_is_featured_gallery_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='student',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='tags',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
