# Generated by Django 5.2.1 on 2025-06-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0009_remove_gallery_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='caption',
        ),
    ]
