# Generated by Django 5.2.1 on 2025-07-24 21:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0010_remove_gallery_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mugshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='mugshots')),
                ('crime', models.TextField()),
                ('grade', models.CharField(max_length=10)),
                ('charges', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mugshot',
                'verbose_name_plural': 'Mugshots',
                'ordering': ['name'],
            },
        ),
    ]
