# Generated by Django 5.2.1 on 2025-07-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0011_mugshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mugshots',
            options={'ordering': ['name'], 'verbose_name': 'Student Photo', 'verbose_name_plural': 'Student Photos'},
        ),
        migrations.RemoveField(
            model_name='mugshots',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='mugshots',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='mugshots',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='mugshots',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='mugshots',
            name='updated_at',
        ),
    ]
