# Generated by Django 5.2.1 on 2025-07-25 23:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0012_alter_mugshots_options_remove_mugshots_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='slideshow')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in slideshow')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Slide',
                'verbose_name_plural': 'Homepage Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
