# Generated by Django 5.2.1 on 2025-07-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0013_homepageslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrefectQuote',
        ),
    ]
