# Generated by Django 5.2.1 on 2025-07-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0014_remove_prefectquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslide',
            name='image',
            field=models.TextField(help_text='Cloudinary URL or external image URL'),
        ),
    ]
