# Generated by Django 5.2.1 on 2025-07-25 23:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0015_update_homepage_slide_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslide',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='slideshow'),
        ),
    ]
