# Generated by Django 5.2.1 on 2025-07-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbookBackend', '0016_update_models_for_cloudinary_uploads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mugshots',
            new_name='Mugshot',
        ),
        migrations.AlterModelTable(
            name='mugshot',
            table='yearbookBackend_mugshots',
        ),
    ]
